import { createClient } from '@supabase/supabase-js'
import './style.css'

const supabase=createClient('https://wdimzayfvtlrxljpsvza.supabase.co','sb_publishable_FZwX09JGrJt3Q9WXW3V1dQ_-g9aegh4')
const app=document.querySelector('#app')
const money=v=>`${Number(v||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} ₺`
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const dt=v=>v?new Date(v).toLocaleString('tr-TR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'
let state={user:null,sellers:[],branches:[],orders:[],tasks:[],incidents:[],stock:[],couriers:[],shifts:[],suppliers:[],purchaseOrders:[],cash:[],support:[],campaigns:[],activeSeller:'all',view:'overview'}

const views=[['overview','⌂','Genel Bakış'],['orders','▤','Siparişler'],['branches','⌘','Şubeler'],['tasks','☑','Görevler'],['incidents','⚠','Olaylar'],['stock','◫','Stok'],['couriers','🛵','Kurye'],['shifts','◷','Vardiya'],['suppliers','⌑','Tedarik'],['finance','₺','Finans'],['support','☏','Destek'],['campaigns','◉','Kampanya']]

async function boot(){const {data:{session}}=await supabase.auth.getSession();state.user=session?.user||null;if(!state.user)return login();await load();render()}
function login(){app.innerHTML=`<main class="login"><section><div class="x">X</div><h1>ORYVEX FOOD OPS</h1><p>TIKLADOY + BURGERMY işletim ve takip merkezi</p><input id="email" type="email" placeholder="E-posta"><input id="password" type="password" placeholder="Şifre"><button id="login">Giriş Yap</button><small id="status"></small></section></main>`;document.querySelector('#login').onclick=async()=>{const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;const {error}=await supabase.auth.signInWithPassword({email,password});if(error){document.querySelector('#status').textContent=error.message;return}boot()}}
async function load(){const {data:members}=await supabase.from('seller_members').select('seller_id,role,sellers(id,name,slug)').eq('user_id',state.user.id).eq('is_active',true);state.sellers=(members||[]).map(m=>({...m.sellers,role:m.role})).filter(Boolean);const sellerIds=state.sellers.map(s=>s.id);if(!sellerIds.length)return;const results=await Promise.all([
  supabase.from('branches').select('*').in('seller_id',sellerIds).order('name'),
  supabase.from('orders').select('id,order_no,seller_id,status,payment_status,payment_method,total_amount,created_at,branch_id,fulfillment_type').in('seller_id',sellerIds).order('created_at',{ascending:false}).limit(150),
  supabase.from('ops_tasks').select('*').in('seller_id',sellerIds).order('created_at',{ascending:false}).limit(150),
  supabase.from('ops_incidents').select('*').in('seller_id',sellerIds).order('created_at',{ascending:false}).limit(150),
  supabase.from('ops_stock_items').select('*').in('seller_id',sellerIds).eq('is_active',true).order('name'),
  supabase.from('ops_couriers').select('*').in('seller_id',sellerIds).eq('is_active',true).order('display_name'),
  supabase.from('ops_shifts').select('*').in('seller_id',sellerIds).order('starts_at',{ascending:true}).limit(150),
  supabase.from('ops_suppliers').select('*').in('seller_id',sellerIds).eq('is_active',true).order('name'),
  supabase.from('ops_purchase_orders').select('*').in('seller_id',sellerIds).order('created_at',{ascending:false}).limit(100),
  supabase.from('ops_cash_entries').select('*').in('seller_id',sellerIds).order('entry_date',{ascending:false}).limit(200),
  supabase.from('ops_support_tickets').select('*').in('seller_id',sellerIds).order('created_at',{ascending:false}).limit(150),
  supabase.from('ops_campaigns').select('*').in('seller_id',sellerIds).order('created_at',{ascending:false}).limit(100)
]);
  [state.branches,state.orders,state.tasks,state.incidents,state.stock,state.couriers,state.shifts,state.suppliers,state.purchaseOrders,state.cash,state.support,state.campaigns]=results.map(r=>r.data||[])
}
const filtered=a=>state.activeSeller==='all'?a:a.filter(x=>x.seller_id===state.activeSeller)
const sellerName=id=>state.sellers.find(s=>s.id===id)?.name||'Marka'
const branchName=id=>state.branches.find(b=>b.id===id)?.name||'—'
const activeSellerId=()=>state.activeSeller==='all'?state.sellers[0]?.id:state.activeSeller
const labelStatus=s=>({received:'Yeni',preparing:'Hazırlanıyor',courier_assigned:'Kurye Atandı',on_the_way:'Yolda',delivered:'Teslim',cancelled:'İptal',todo:'Bekliyor',in_progress:'Devam',blocked:'Bloke',done:'Tamam',open:'Açık',investigating:'İnceleniyor',resolved:'Çözüldü',closed:'Kapalı'})[s]||s

function render(){app.innerHTML=`<div class="shell"><aside><div class="brand"><span>X</span><div><b>ORYVEX</b><small>FOOD OPS</small></div></div>${views.map(([id,icon,label])=>`<button class="nav ${state.view===id?'active':''}" data-view="${id}">${icon} ${label}</button>`).join('')}<div class="brands">${['all',...state.sellers.map(s=>s.id)].map(id=>{const s=state.sellers.find(x=>x.id===id);return `<button data-seller="${id}" class="${state.activeSeller===id?'sel':''}">${id==='all'?'TÜM MARKALAR':esc(s?.name)}</button>`}).join('')}</div></aside><main><header><div><small>İŞLETİM MERKEZİ</small><h1>${viewTitle()}</h1></div><div><button id="refresh">↻ Yenile</button><button id="logout">Çıkış</button></div></header><div id="content">${renderView()}</div></main></div>`;bind()}
function viewTitle(){return views.find(v=>v[0]===state.view)?.[2]||'Genel Bakış'}
function renderView(){return ({overview:overviewPanel,orders:ordersPanel,branches:branchesPanel,tasks:tasksPanel,incidents:incidentsPanel,stock:stockPanel,couriers:couriersPanel,shifts:shiftsPanel,suppliers:suppliersPanel,finance:financePanel,support:supportPanel,campaigns:campaignsPanel})[state.view]?.()||overviewPanel()}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelectorAll('[data-seller]').forEach(b=>b.onclick=()=>{state.activeSeller=b.dataset.seller;render()});document.querySelector('#refresh').onclick=async()=>{await load();render()};document.querySelector('#logout').onclick=async()=>{await supabase.auth.signOut();state.user=null;login()};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.(b))}

function overviewPanel(){const orders=filtered(state.orders),tasks=filtered(state.tasks),incidents=filtered(state.incidents),stock=filtered(state.stock),couriers=filtered(state.couriers),cash=filtered(state.cash),support=filtered(state.support);const today=new Date().toISOString().slice(0,10),todayOrders=orders.filter(o=>o.created_at?.slice(0,10)===today),revenue=todayOrders.filter(o=>o.payment_status==='paid'||o.status==='delivered').reduce((s,o)=>s+Number(o.total_amount||0),0),open=orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length,critical=incidents.filter(i=>!['resolved','closed'].includes(i.status)&&['high','critical'].includes(i.severity)).length,lowStock=stock.filter(s=>Number(s.current_qty)<=Number(s.minimum_qty)).length,activeCouriers=couriers.filter(c=>['available','busy'].includes(c.status)).length,todayCash=cash.filter(x=>x.entry_date===today),cashNet=todayCash.reduce((s,x)=>s+(x.type==='income'?Number(x.amount):-Number(x.amount)),0),openSupport=support.filter(x=>!['resolved','closed'].includes(x.status)).length;return `<section class="metrics"><article><span>Bugünkü Sipariş</span><b>${todayOrders.length}</b></article><article><span>Açık Sipariş</span><b>${open}</b></article><article><span>Bugünkü Ciro</span><b>${money(revenue)}</b></article><article><span>Aktif Kurye</span><b>${activeCouriers}</b></article><article><span>Düşük Stok</span><b>${lowStock}</b></article><article><span>Açık Destek</span><b>${openSupport}</b></article><article><span>Günlük Nakit Net</span><b>${money(cashNet)}</b></article><article><span>Kritik Olay</span><b>${critical}</b></article></section><section class="grid"><article class="panel"><div class="ph"><h2>Canlı Siparişler</h2><button data-view-jump="orders">${open} açık</button></div>${orderRows(orders.slice(0,10))}</article><article class="panel"><div class="ph"><h2>Görevler</h2><button data-action="newTask">+ Görev</button></div>${taskRows(tasks.filter(t=>!['done','cancelled'].includes(t.status)).slice(0,9))}</article><article class="panel"><div class="ph"><h2>Stok Uyarıları</h2><span>${lowStock} kritik</span></div>${stockRows(stock.filter(s=>Number(s.current_qty)<=Number(s.minimum_qty)).slice(0,9))}</article><article class="panel"><div class="ph"><h2>Müşteri Destek</h2><span>${openSupport} açık</span></div>${supportRows(support.filter(t=>!['resolved','closed'].includes(t.status)).slice(0,9))}</article></section>`}
function ordersPanel(){const a=filtered(state.orders);return pagePanel('Sipariş Yönetimi',`${a.length} kayıt`,orderRows(a,true))}
function branchesPanel(){const a=filtered(state.branches);return pagePanel('Şubeler',`<button data-action="newBranch">+ Şube</button>`,a.map(x=>`<div class="record"><div><b>${esc(x.name)}</b><small>${sellerName(x.seller_id)} · ${x.is_active?'Aktif':'Pasif'}</small></div><div class="chips"><span>Min ${money(x.minimum_order)}</span><span>Teslimat ${money(x.delivery_fee)}</span><span>${x.supports_pickup?'Gel-Al ✓':'Gel-Al —'}</span></div></div>`).join('')||empty('Şube kaydı yok.'))}
function tasksPanel(){return pagePanel('Görev Yönetimi','<button data-action="newTask">+ Görev</button>',taskRows(filtered(state.tasks),true))}
function incidentsPanel(){const a=filtered(state.incidents);return pagePanel('Olay / Sorun Takibi','<button data-action="newIncident">+ Olay</button>',a.map(x=>`<div class="record"><div><b>${esc(x.title)}</b><small>${esc(x.type)} · ${esc(x.severity)} · ${dt(x.created_at)}</small></div><select data-action="incidentStatus" data-id="${x.id}">${['open','investigating','resolved','closed'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')||empty('Olay kaydı yok.'))}
function stockPanel(){return pagePanel('Stok Yönetimi','<button data-action="newStock">+ Stok Kalemi</button>',stockRows(filtered(state.stock),true))}
function couriersPanel(){const a=filtered(state.couriers);return pagePanel('Kurye Yönetimi','<button data-action="newCourier">+ Kurye</button>',a.map(c=>`<div class="record"><div><b>${esc(c.display_name)}</b><small>${esc(c.vehicle_type)} · ${branchName(c.branch_id)}</small></div><select data-action="courierStatus" data-id="${c.id}">${['offline','available','busy','break'].map(s=>`<option ${s===c.status?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')||empty('Kurye kaydı yok.'))}
function shiftsPanel(){const a=filtered(state.shifts);return pagePanel('Personel / Vardiya','<button data-action="newShift">+ Vardiya</button>',a.map(s=>`<div class="record"><div><b>${esc(s.role)}</b><small>${branchName(s.branch_id)} · ${dt(s.starts_at)} → ${dt(s.ends_at)}</small></div><span class="badge">${esc(s.status)}</span></div>`).join('')||empty('Vardiya kaydı yok.'))}
function suppliersPanel(){const suppliers=filtered(state.suppliers),po=filtered(state.purchaseOrders);return `<section class="split"><article class="panel"><div class="ph"><h2>Tedarikçiler</h2><button data-action="newSupplier">+ Tedarikçi</button></div>${suppliers.map(s=>`<div class="record"><div><b>${esc(s.name)}</b><small>${esc(s.contact_name||'')} ${esc(s.phone||'')}</small></div><span>${s.payment_terms_days||0} gün</span></div>`).join('')||empty('Tedarikçi yok.')}</article><article class="panel"><div class="ph"><h2>Satın Alma Siparişleri</h2><button data-action="newPurchase">+ Satın Alma</button></div>${po.map(p=>`<div class="record"><div><b>${esc(p.po_no)}</b><small>${esc(p.status)} · ${dt(p.expected_at)}</small></div><strong>${money(p.total_amount)}</strong></div>`).join('')||empty('Satın alma kaydı yok.')}</article></section>`}
function financePanel(){const a=filtered(state.cash);const income=a.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0),expense=a.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0);return `<section class="metrics finance"><article><span>Gelir</span><b>${money(income)}</b></article><article><span>Gider</span><b>${money(expense)}</b></article><article><span>Net</span><b>${money(income-expense)}</b></article></section>${pagePanel('Kasa / Finans','<button data-action="newCash">+ Kasa Hareketi</button>',a.map(x=>`<div class="record"><div><b>${esc(x.category)}</b><small>${x.entry_date} · ${esc(x.description||'')}</small></div><strong class="${x.type}">${x.type==='income'?'+':'-'}${money(x.amount)}</strong></div>`).join('')||empty('Kasa hareketi yok.'))}`}
function supportPanel(){return pagePanel('Müşteri Destek','<button data-action="newSupport">+ Destek Kaydı</button>',supportRows(filtered(state.support),true))}
function campaignsPanel(){const a=filtered(state.campaigns);return pagePanel('Kampanya Yönetimi','<button data-action="newCampaign">+ Kampanya</button>',a.map(c=>`<div class="record"><div><b>${esc(c.name)}</b><small>${esc(c.channel)} · ${dt(c.starts_at)} → ${dt(c.ends_at)}</small></div><div class="chips"><span>${esc(c.status)}</span><strong>${money(c.budget)}</strong></div></div>`).join('')||empty('Kampanya yok.'))}

function pagePanel(title,action,body){return `<section class="panel page"><div class="ph"><h2>${title}</h2><div>${action}</div></div>${body}</section>`}
const empty=t=>`<p class="empty">${t}</p>`
function orderRows(a,editable=false){return a.map(o=>`<div class="record"><div><b>${esc(o.order_no)}</b><small>${sellerName(o.seller_id)} · ${branchName(o.branch_id)} · ${dt(o.created_at)} · ${esc(o.fulfillment_type||'')}</small></div>${editable?`<select data-action="orderStatus" data-id="${o.id}">${['received','preparing','courier_assigned','on_the_way','delivered','cancelled'].map(s=>`<option value="${s}" ${s===o.status?'selected':''}>${labelStatus(s)}</option>`).join('')}</select>`:`<span class="badge ${o.status}">${labelStatus(o.status)}</span>`}<strong>${money(o.total_amount)}</strong></div>`).join('')||empty('Sipariş yok.')}
function taskRows(a,editable=false){return a.map(t=>`<div class="record"><div class="with-dot"><i class="dot ${t.priority}"></i><div><b>${esc(t.title)}</b><small>${esc(t.category)} · ${dt(t.due_at)}</small></div></div>${editable?`<select data-action="taskStatus" data-id="${t.id}">${['todo','in_progress','blocked','done','cancelled'].map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select>`:`<span>${labelStatus(t.status)}</span>`}</div>`).join('')||empty('Görev yok.')}
function stockRows(a,editable=false){return a.map(s=>`<div class="record"><div><b>${esc(s.name)}</b><small>${sellerName(s.seller_id)} · min ${Number(s.minimum_qty)} ${esc(s.unit)}</small></div>${editable?`<button data-action="stockAdjust" data-id="${s.id}" data-name="${esc(s.name)}">${Number(s.current_qty)} ${esc(s.unit)} ✎</button>`:`<strong>${Number(s.current_qty)} ${esc(s.unit)}</strong>`}</div>`).join('')||empty('Stok kaydı yok.')}
function supportRows(a,editable=false){return a.map(t=>`<div class="record"><div class="with-dot"><i class="dot ${t.priority}"></i><div><b>${esc(t.subject)}</b><small>${esc(t.channel)} · ${dt(t.created_at)}</small></div></div>${editable?`<select data-action="supportStatus" data-id="${t.id}">${['open','waiting_customer','in_progress','resolved','closed'].map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select>`:`<span>${esc(t.status)}</span>`}</div>`).join('')||empty('Destek kaydı yok.')}

const actions={
  async orderStatus(b){await patch('orders',b.dataset.id,{status:b.value,updated_at:new Date().toISOString()})},
  async taskStatus(b){await patch('ops_tasks',b.dataset.id,{status:b.value,updated_at:new Date().toISOString()})},
  async incidentStatus(b){await patch('ops_incidents',b.dataset.id,{status:b.value,resolved_at:['resolved','closed'].includes(b.value)?new Date().toISOString():null,updated_at:new Date().toISOString()})},
  async courierStatus(b){await patch('ops_couriers',b.dataset.id,{status:b.value,last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()})},
  async supportStatus(b){await patch('ops_support_tickets',b.dataset.id,{status:b.value,updated_at:new Date().toISOString()})},
  async stockAdjust(b){const q=prompt(`${b.dataset.name} yeni miktar`);if(q===null||isNaN(Number(q)))return;await patch('ops_stock_items',b.dataset.id,{current_qty:Number(q),updated_at:new Date().toISOString()})},
  async newTask(){const title=prompt('Görev başlığı');if(!title)return;await insert('ops_tasks',{seller_id:activeSellerId(),title,priority:'medium',status:'todo',category:'operation',created_by:state.user.id})},
  async newIncident(){const title=prompt('Olay / sorun başlığı');if(!title)return;await insert('ops_incidents',{seller_id:activeSellerId(),title,type:'other',severity:'medium',status:'open',created_by:state.user.id})},
  async newStock(){const name=prompt('Stok kalemi');if(!name)return;const min=Number(prompt('Minimum stok','5')||0);await insert('ops_stock_items',{seller_id:activeSellerId(),name,unit:'adet',current_qty:0,minimum_qty:min,target_qty:min*3,is_active:true})},
  async newCourier(){const display_name=prompt('Kurye adı');if(!display_name)return;const phone=prompt('Telefon','')||null;await insert('ops_couriers',{seller_id:activeSellerId(),display_name,phone,vehicle_type:'motorcycle',status:'offline',is_active:true})},
  async newShift(){const role=prompt('Görev / rol','personel')||'personel';const starts_at=prompt('Başlangıç (YYYY-MM-DD HH:MM)');if(!starts_at)return;const ends_at=prompt('Bitiş (YYYY-MM-DD HH:MM)');if(!ends_at)return;await insert('ops_shifts',{seller_id:activeSellerId(),role,starts_at:new Date(starts_at).toISOString(),ends_at:new Date(ends_at).toISOString(),status:'scheduled'})},
  async newSupplier(){const name=prompt('Tedarikçi adı');if(!name)return;const phone=prompt('Telefon','')||null;await insert('ops_suppliers',{seller_id:activeSellerId(),name,phone,is_active:true})},
  async newPurchase(){const total_amount=Number(prompt('Satın alma toplamı','0')||0);const po_no=`PO-${Date.now().toString().slice(-7)}`;await insert('ops_purchase_orders',{seller_id:activeSellerId(),po_no,total_amount,status:'draft',created_by:state.user.id})},
  async newCash(){const type=(prompt('Tür: income veya expense','expense')||'expense').toLowerCase();if(!['income','expense'].includes(type))return alert('income veya expense yaz.');const amount=Number(prompt('Tutar','0')||0);if(amount<=0)return;const category=prompt('Kategori','other')||'other';const description=prompt('Açıklama','')||null;await insert('ops_cash_entries',{seller_id:activeSellerId(),type,amount,category,description,created_by:state.user.id})},
  async newSupport(){const subject=prompt('Destek konusu');if(!subject)return;await insert('ops_support_tickets',{seller_id:activeSellerId(),subject,channel:'app',priority:'medium',status:'open'})},
  async newCampaign(){const name=prompt('Kampanya adı');if(!name)return;const budget=Number(prompt('Bütçe','0')||0);await insert('ops_campaigns',{seller_id:activeSellerId(),name,budget,channel:'app',status:'draft',created_by:state.user.id})},
  async newBranch(){alert('Şube açılışı ana işletme ayarından yapılacak. Bu panel mevcut şubeleri ve operasyon durumlarını yönetir.')}
}
async function patch(table,id,data){const {error}=await supabase.from(table).update(data).eq('id',id);if(error)return alert(error.message);await load();render()}
async function insert(table,data){if(!data.seller_id)return alert('Önce bir marka seç.');const {error}=await supabase.from(table).insert(data);if(error)return alert(error.message);await load();render()}

boot()
