-- Keep read access separate from mutations so SELECT does not evaluate duplicate permissive policies.

-- AI insights
drop policy if exists santiye_ai_insights_write on public.santiye_ai_insights;
create policy santiye_ai_insights_insert on public.santiye_ai_insights for insert to authenticated with check (exists (select 1 from public.santiye_projects p where p.id=santiye_ai_insights.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager'])));
create policy santiye_ai_insights_update on public.santiye_ai_insights for update to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_ai_insights.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager']))) with check (exists (select 1 from public.santiye_projects p where p.id=santiye_ai_insights.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager'])));
create policy santiye_ai_insights_delete on public.santiye_ai_insights for delete to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_ai_insights.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager'])));

-- Cost snapshots
drop policy if exists santiye_cost_snapshots_write on public.santiye_cost_snapshots;
create policy santiye_cost_snapshots_insert on public.santiye_cost_snapshots for insert to authenticated with check (exists (select 1 from public.santiye_projects p where p.id=santiye_cost_snapshots.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','accounting'])));
create policy santiye_cost_snapshots_update on public.santiye_cost_snapshots for update to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_cost_snapshots.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','accounting']))) with check (exists (select 1 from public.santiye_projects p where p.id=santiye_cost_snapshots.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','accounting'])));
create policy santiye_cost_snapshots_delete on public.santiye_cost_snapshots for delete to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_cost_snapshots.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','accounting'])));

-- Delay risks
drop policy if exists santiye_delay_risks_write on public.santiye_delay_risks;
create policy santiye_delay_risks_insert on public.santiye_delay_risks for insert to authenticated with check (exists (select 1 from public.santiye_projects p where p.id=santiye_delay_risks.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager'])));
create policy santiye_delay_risks_update on public.santiye_delay_risks for update to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_delay_risks.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager']))) with check (exists (select 1 from public.santiye_projects p where p.id=santiye_delay_risks.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager'])));
create policy santiye_delay_risks_delete on public.santiye_delay_risks for delete to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_delay_risks.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager'])));

-- Inventory
drop policy if exists santiye_inventory_write on public.santiye_inventory;
create policy santiye_inventory_insert on public.santiye_inventory for insert to authenticated with check (exists (select 1 from public.santiye_projects p where p.id=santiye_inventory.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager','purchasing'])));
create policy santiye_inventory_update on public.santiye_inventory for update to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_inventory.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager','purchasing']))) with check (exists (select 1 from public.santiye_projects p where p.id=santiye_inventory.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager','purchasing'])));
create policy santiye_inventory_delete on public.santiye_inventory for delete to authenticated using (exists (select 1 from public.santiye_projects p where p.id=santiye_inventory.project_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','site_manager','purchasing'])));

-- Purchase order items
drop policy if exists santiye_purchase_order_items_write on public.santiye_purchase_order_items;
create policy santiye_purchase_order_items_insert on public.santiye_purchase_order_items for insert to authenticated with check (exists (select 1 from public.santiye_purchase_orders o join public.santiye_projects p on p.id=o.project_id where o.id=santiye_purchase_order_items.purchase_order_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','purchasing'])));
create policy santiye_purchase_order_items_update on public.santiye_purchase_order_items for update to authenticated using (exists (select 1 from public.santiye_purchase_orders o join public.santiye_projects p on p.id=o.project_id where o.id=santiye_purchase_order_items.purchase_order_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','purchasing']))) with check (exists (select 1 from public.santiye_purchase_orders o join public.santiye_projects p on p.id=o.project_id where o.id=santiye_purchase_order_items.purchase_order_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','purchasing'])));
create policy santiye_purchase_order_items_delete on public.santiye_purchase_order_items for delete to authenticated using (exists (select 1 from public.santiye_purchase_orders o join public.santiye_projects p on p.id=o.project_id where o.id=santiye_purchase_order_items.purchase_order_id and public.santiye_has_company_role(p.company_id,array['owner','project_manager','purchasing'])));
