import { supabase } from './supabase.js'

let products=[];
let cart=JSON.parse(localStorage.getItem('tikladoy_cart')||'[]');
let session=null;
let authMode='login';
const app=document.querySelector('#app');
const money=v=>`${Number(v).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} ₺`;
const iconFor=name=>/tost|sandviç/i.test(name)?'breakfast_dining':/salata/i.test(name)?'nutrition':/peynir|kahvalt/i.test(name)?'lunch_dining':'restaurant';
const saveCart=()=>localStorage.setItem('tikladoy_cart',JSON.stringify(cart));

async function loadProducts(){
 const {data,error}=await supabase.from('products').select('id,name,price,description,image_url,is_featured,seller_id').eq('is_active',true).order('created_at');
 if(error){console.error('Supabase products:',error);return;}
 products=data||[];
}
function shell(content,active='home'){app.innerHTML=`<div class="app"><header class="top"><div class="brand">TIKLADOY</div><span class="material-symbols-outlined icon">${session?'account_circle':'notifications'}</span></header>${content}<nav class="bottom">${[['home','Ana Sayfa'],['search','Keşfet'],['shopping_cart','Sepet'],['person','Hesabım']].map(([i,t])=>`<div class="nav ${active===i?'active':''}" data-nav="${i}"><span class="material-symbols-outlined">${i}</span>${t}${i==='shopping_cart'&&cart.length?` <b class="badge">${cart.length}</b>`:''}</div>`).join('')}</nav></div>`;document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>route(x.dataset.nav));}
function productCard(p,i){return `<article class="card"><div class="photo">${p.image_url?`<img src="${p.image_url}" alt="${p.name}" style="width:100%;height:100%;object-fit:cover">`:`<span class="material-symbols-outlined" style="font-size:48px">${iconFor(p.name)}</span>`}</div><div class="cardbody"><button class="add" data-add="${i}">+</button><h3>${p.name}</h3><span class="price">${money(p.price)}</span></div></article>`}
function home(){shell(`<section class="hero"><h1>Ne yiyeceksen,<br>TIKLADOY.</h1><p>Hazır yemek, kahvaltı, atıştırmalık ve günlük ihtiyaçlar tek yerde.</p></section><input class="search" id="search" placeholder="Ne yemek istersin?"/><section class="section"><div class="cats"><div class="chip active">Tümü</div><div class="chip">Ev Yemekleri</div><div class="chip">Kahvaltı</div><div class="chip">Tost</div><div class="chip">Salata</div></div></section><section class="section"><h2>Bugün ne yiyelim?</h2><div class="grid" id="productGrid">${products.map(productCard).join('')}</div></section>`);bindProducts();document.querySelector('#search').oninput=e=>{const q=e.target.value.toLocaleLowerCase('tr');document.querySelector('#productGrid').innerHTML=products.filter(p=>p.name.toLocaleLowerCase('tr').includes(q)||(p.description||'').toLocaleLowerCase('tr').includes(q)).map(productCard).join('');bindProducts()}}
function bindProducts(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{cart.push(products[+b.dataset.add]);saveCart();home()})}
function cartPage(){const total=cart.reduce((s,p)=>s+Number(p.price),0);shell(`<section class="hero"><h1>Sepetim</h1><p>${cart.length} ürün</p></section><div class="panel">${cart.length?cart.map((p,i)=>`<div class="row"><div><b>${p.name}</b><div class="muted">1 adet</div></div><div><span class="price">${money(p.price)}</span> <button class="back" data-del="${i}">×</button></div></div>`).join(''):`<p class="muted">Sepetin henüz boş.</p>`}${cart.length?`<div class="row"><b>Toplam</b><b class="price">${money(total)}</b></div><button class="btn" id="checkout">Ödemeye Geç</button>`:''}</div>`,'shopping_cart');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.del,1);saveCart();cartPage()});if(document.querySelector('#checkout'))document.querySelector('#checkout').onclick=()=>session?checkout():authPage('Sipariş vermek için giriş yap.')}
function checkout(){const total=cart.reduce((s,p)=>s+Number(p.price),0);shell(`<section class="hero"><h1>Ödeme</h1><p>Siparişini tamamla.</p></section><div class="panel"><div class="row"><span>Teslimat Adresi</span><b>V1 Test Adresi</b></div><div class="row"><span>Ödeme</span><b>Test / Tahsilat Yok</b></div><div class="row"><b>Toplam</b><b class="price">${money(total)}</b></div><button class="btn" id="complete">Siparişi Oluştur</button><p class="muted small">V1 test akışı: gerçek ödeme henüz tahsil edilmez.</p></div>`,'shopping_cart');document.querySelector('#complete').onclick=createOrder}
async function createOrder(){
 const btn=document.querySelector('#complete');btn.disabled=true;btn.textContent='Sipariş oluşturuluyor…';
 if(!session?.user){authPage('Oturum süren dolmuş. Tekrar giriş yap.');return;}
 const sellerId=cart[0]?.seller_id;
 const subtotal=cart.reduce((s,p)=>s+Number(p.price),0);
 const orderNo=`TKD-${Date.now().toString().slice(-8)}`;
 const {data:order,error}=await supabase.from('orders').insert({order_no:orderNo,user_id:session.user.id,seller_id:sellerId,status:'received',payment_status:'pending',payment_method:'test',subtotal,delivery_fee:0,discount_amount:0,total_amount:subtotal,estimated_min:20,estimated_max:30}).select().single();
 if(error){console.error(error);showOrderError(error.message);return;}
 const items=cart.map(p=>({order_id:order.id,product_id:p.id,product_name:p.name,quantity:1,unit_price:Number(p.price),line_total:Number(p.price)}));
 const {error:itemError}=await supabase.from('order_items').insert(items);
 if(itemError){console.error(itemError);showOrderError(itemError.message);return;}
 cart=[];saveCart();success(orderNo,subtotal);
}
function showOrderError(message){shell(`<section class="hero"><h1>Sipariş tamamlanamadı</h1><p>Bağlantı çalışıyor; yazma iznini tamamlamamız gerekiyor.</p></section><div class="panel"><div class="status err">${message}</div><button class="btn" id="backCart">Sepete Dön</button></div>`,'shopping_cart');document.querySelector('#backCart').onclick=cartPage}
function success(orderNo,total){shell(`<section class="hero" style="text-align:center"><span class="material-symbols-outlined icon" style="font-size:80px">check_circle</span><h1>Siparişin Alındı!</h1><p>Lezzetin hazırlanıyor.</p></section><div class="panel"><div class="row"><span>Sipariş No</span><b>${orderNo}</b></div><div class="row"><span>Toplam</span><b class="price">${money(total)}</b></div><div class="row"><span>Tahmini Teslimat</span><b class="price">20–30 dk</b></div><button class="btn" id="goHome">Ana Sayfaya Dön</button></div>`);document.querySelector('#goHome').onclick=()=>{location.hash='home';home()}}
function authPage(note=''){shell(`<section class="hero"><h1>${session?'Hesabım':'Hoş geldin'}</h1><p>${session?'Hesap ve sipariş bilgilerin.':'Siparişlerini takip etmek için giriş yap veya hesap oluştur.'}</p></section>${note?`<div class="status">${note}</div>`:''}${session?accountPanel():authForm()}`,'person');bindAuth()}
function authForm(){return `<div class="tabs"><button class="tab ${authMode==='login'?'active':''}" data-mode="login">Giriş Yap</button><button class="tab ${authMode==='register'?'active':''}" data-mode="register">Kayıt Ol</button></div>${authMode==='register'?'<input class="field" id="name" placeholder="Ad Soyad"/>':''}<input class="field" id="email" type="email" placeholder="E-posta"/><input class="field" id="password" type="password" placeholder="Şifre"/><div class="panel"><button class="btn" id="authSubmit">${authMode==='login'?'Giriş Yap':'Hesap Oluştur'}</button><div id="authStatus"></div></div>`}
function accountPanel(){const email=session?.user?.email||'';return `<div class="panel"><div class="userbox"><div class="avatar"><span class="material-symbols-outlined">person</span></div><div><b>${email}</b><div class="muted small">Supabase kullanıcı hesabı</div></div></div><div class="row"><span>Adreslerim</span><span>›</span></div><div class="row"><span>Siparişlerim</span><span>›</span></div><button class="btn secondary" id="logout">Çıkış Yap</button></div>`}
function bindAuth(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;authPage()});if(document.querySelector('#logout'))document.querySelector('#logout').onclick=async()=>{await supabase.auth.signOut();session=null;authPage('Çıkış yapıldı.')};if(document.querySelector('#authSubmit'))document.querySelector('#authSubmit').onclick=submitAuth}
async function submitAuth(){const email=document.querySelector('#email').value.trim();const password=document.querySelector('#password').value;const name=document.querySelector('#name')?.value.trim();const status=document.querySelector('#authStatus');status.innerHTML='<div class="status">İşlem yapılıyor…</div>';if(authMode==='login'){const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){status.innerHTML=`<div class="status err">${error.message}</div>`;return;}session=data.session;authPage('Giriş başarılı.');return;}const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error){status.innerHTML=`<div class="status err">${error.message}</div>`;return;}session=data.session;if(session)authPage('Hesabın oluşturuldu ve giriş yapıldı.');else status.innerHTML='<div class="status ok">Hesabın oluşturuldu. E-posta doğrulama bağlantısını kontrol et.</div>'}
function route(r){if(r==='shopping_cart')return cartPage();if(r==='person')return authPage();home()}
async function start(){shell(`<section class="hero"><h1>TIKLADOY</h1><p>Supabase'e bağlanıyor…</p></section>`);const {data:{session:s}}=await supabase.auth.getSession();session=s;supabase.auth.onAuthStateChange((_event,s)=>{session=s});await loadProducts();route(location.hash.slice(1)||'home')}
window.addEventListener('hashchange',()=>route(location.hash.slice(1)||'home'));
start();
