import { supabase } from './supabase.js'

let products=[];
let cart=[];
const app=document.querySelector('#app');
const money=v=>`${Number(v).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} ₺`;
const iconFor=name=>/tost|sandviç/i.test(name)?'breakfast_dining':/salata/i.test(name)?'nutrition':/peynir|kahvalt/i.test(name)?'lunch_dining':'restaurant';

async function loadProducts(){
 const {data,error}=await supabase.from('products').select('id,name,price,description,image_url,is_featured').eq('is_active',true).order('created_at');
 if(error){console.error('Supabase products:',error);return;}
 products=data||[];
}
function shell(content,active='home'){app.innerHTML=`<div class="app"><header class="top"><div class="brand">TIKLADOY</div><span class="material-symbols-outlined icon">notifications</span></header>${content}<nav class="bottom">${[['home','Ana Sayfa'],['search','Keşfet'],['shopping_cart','Sepet'],['person','Hesabım']].map(([i,t])=>`<div class="nav ${active===i?'active':''}" data-nav="${i}"><span class="material-symbols-outlined">${i}</span>${t}${i==='shopping_cart'&&cart.length?` <b class="badge">${cart.length}</b>`:''}</div>`).join('')}</nav></div>`;document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>route(x.dataset.nav));}
function productCard(p,i){return `<article class="card"><div class="photo">${p.image_url?`<img src="${p.image_url}" alt="${p.name}" style="width:100%;height:100%;object-fit:cover">`:`<span class="material-symbols-outlined" style="font-size:48px">${iconFor(p.name)}</span>`}</div><div class="cardbody"><button class="add" data-add="${i}">+</button><h3>${p.name}</h3><span class="price">${money(p.price)}</span></div></article>`}
function home(){shell(`<section class="hero"><h1>Ne yiyeceksen,<br>TIKLADOY.</h1><p>Hazır yemek, kahvaltı, atıştırmalık ve günlük ihtiyaçlar tek yerde.</p></section><input class="search" id="search" placeholder="Ne yemek istersin?"/><section class="section"><div class="cats"><div class="chip active">Tümü</div><div class="chip">Ev Yemekleri</div><div class="chip">Kahvaltı</div><div class="chip">Tost</div><div class="chip">Salata</div></div></section><section class="section"><h2>Bugün ne yiyelim?</h2><div class="grid" id="productGrid">${products.map(productCard).join('')}</div></section>`);bindProducts();document.querySelector('#search').oninput=e=>{const q=e.target.value.toLocaleLowerCase('tr');document.querySelector('#productGrid').innerHTML=products.filter(p=>p.name.toLocaleLowerCase('tr').includes(q)||(p.description||'').toLocaleLowerCase('tr').includes(q)).map(productCard).join('');bindProducts()}}
function bindProducts(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{cart.push(products[+b.dataset.add]);home()})}
function cartPage(){const total=cart.reduce((s,p)=>s+Number(p.price),0);shell(`<section class="hero"><h1>Sepetim</h1><p>${cart.length} ürün</p></section><div class="panel">${cart.length?cart.map((p,i)=>`<div class="row"><div><b>${p.name}</b><div class="muted">1 adet</div></div><div><span class="price">${money(p.price)}</span> <button class="back" data-del="${i}">×</button></div></div>`).join(''):`<p class="muted">Sepetin henüz boş.</p>`}${cart.length?`<div class="row"><b>Toplam</b><b class="price">${money(total)}</b></div><button class="btn" id="checkout">Ödemeye Geç</button>`:''}</div>`,'shopping_cart');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.del,1);cartPage()});if(document.querySelector('#checkout'))document.querySelector('#checkout').onclick=checkout}
function checkout(){shell(`<section class="hero"><h1>Ödeme</h1><p>Siparişini tamamla.</p></section><div class="panel"><div class="row"><span>Teslimat Adresi</span><b>Ev</b></div><div class="row"><span>Ödeme</span><b>Kart ile</b></div><button class="btn" id="complete">Siparişi Onayla</button><p class="muted" style="font-size:12px">V1 test akışı: gerçek ödeme henüz tahsil edilmez.</p></div>`,'shopping_cart');document.querySelector('#complete').onclick=success}
function success(){cart=[];shell(`<section class="hero" style="text-align:center"><span class="material-symbols-outlined icon" style="font-size:80px">check_circle</span><h1>Siparişin Alındı!</h1><p>Lezzetin hazırlanıyor.</p></section><div class="panel"><div class="row"><span>Durum</span><b>Test siparişi</b></div><div class="row"><span>Tahmini Teslimat</span><b class="price">20–30 dk</b></div><button class="btn" id="goHome">Ana Sayfaya Dön</button></div>`);document.querySelector('#goHome').onclick=()=>{location.hash='home';home()}}
function route(r){if(r==='shopping_cart')return cartPage();if(r==='person')return shell(`<section class="hero"><h1>Hesabım</h1><p>Profil, adresler ve siparişlerin.</p></section><div class="panel"><div class="row"><span>Adreslerim</span><span>›</span></div><div class="row"><span>Siparişlerim</span><span>›</span></div><div class="row"><span>TIKLADOY Hakkında</span><span>›</span></div></div>`,'person');home()}
async function start(){shell(`<section class="hero"><h1>TIKLADOY</h1><p>Supabase'e bağlanıyor…</p></section>`);await loadProducts();route(location.hash.slice(1)||'home')}
window.addEventListener('hashchange',()=>route(location.hash.slice(1)||'home'));
start();
