const products=[['4 Çeşit Ev Yemeği','120,00 ₺','restaurant'],['TIKLADOY Peynir Tabağı','185,50 ₺','lunch_dining'],['Karışık Tost','95,00 ₺','breakfast_dining'],['Günlük Salata','89,00 ₺','nutrition']];
let cart=[];
const app=document.querySelector('#app');
function shell(content,active='home'){app.innerHTML=`<div class="app"><header class="top"><div class="brand">TIKLADOY</div><span class="material-symbols-outlined icon">notifications</span></header>${content}<nav class="bottom">${[['home','Ana Sayfa'],['search','Keşfet'],['shopping_cart','Sepet'],['person','Hesabım']].map(([i,t])=>`<div class="nav ${active===i?'active':''}" data-nav="${i}"><span class="material-symbols-outlined">${i}</span>${t}${i==='shopping_cart'&&cart.length?` <b class="badge">${cart.length}</b>`:''}</div>`).join('')}</nav></div>`;document.querySelectorAll('[data-nav]').forEach(x=>x.onclick=()=>route(x.dataset.nav));}
function home(){shell(`<section class="hero"><h1>Ne yiyeceksen,<br>TIKLADOY.</h1><p>Hazır yemek, kahvaltı, atıştırmalık ve günlük ihtiyaçlar tek yerde.</p></section><input class="search" placeholder="Ne yemek istersin?"/><section class="section"><div class="cats"><div class="chip active">Tümü</div><div class="chip">Ev Yemekleri</div><div class="chip">Kahvaltı</div><div class="chip">Tost</div><div class="chip">Salata</div></div></section><section class="section"><h2>Bugün ne yiyelim?</h2><div class="grid">${products.map((p,i)=>`<article class="card"><div class="photo"><span class="material-symbols-outlined" style="font-size:48px">${p[2]}</span></div><div class="cardbody"><button class="add" data-add="${i}">+</button><h3>${p[0]}</h3><span class="price">${p[1]}</span></div></article>`).join('')}</div></section>`);document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{cart.push(products[+b.dataset.add]);home()})}
function cartPage(){shell(`<section class="hero"><h1>Sepetim</h1><p>${cart.length} ürün</p></section><div class="panel">${cart.length?cart.map((p,i)=>`<div class="row"><div><b>${p[0]}</b><div class="muted">1 adet</div></div><div><span class="price">${p[1]}</span> <button class="back" data-del="${i}">×</button></div></div>`).join(''):`<p class="muted">Sepetin henüz boş.</p>`}${cart.length?`<button class="btn" id="checkout">Ödemeye Geç</button>`:''}</div>`,'shopping_cart');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.del,1);cartPage()});if(document.querySelector('#checkout'))document.querySelector('#checkout').onclick=checkout}
function checkout(){shell(`<section class="hero"><h1>Ödeme</h1><p>Siparişini tamamla.</p></section><div class="panel"><div class="row"><span>Teslimat Adresi</span><b>Ev</b></div><div class="row"><span>Ödeme</span><b>Kart ile</b></div><button class="btn" id="complete">Siparişi Onayla</button></div>`,'shopping_cart');document.querySelector('#complete').onclick=success}
function success(){cart=[];shell(`<section class="hero" style="text-align:center"><span class="material-symbols-outlined icon" style="font-size:80px">check_circle</span><h1>Siparişin Alındı!</h1><p>Lezzetin hazırlanıyor.</p></section><div class="panel"><div class="row"><span>Sipariş No</span><b>#TKD-1248</b></div><div class="row"><span>Tahmini Teslimat</span><b class="price">20–30 dk</b></div><button class="btn" onclick="location.hash='home'">Ana Sayfaya Dön</button></div>`)}
function route(r){if(r==='shopping_cart')return cartPage();if(r==='person')return shell(`<section class="hero"><h1>Hesabım</h1><p>Profil, adresler ve siparişlerin.</p></section><div class="panel"><div class="row"><span>Adreslerim</span><span>›</span></div><div class="row"><span>Siparişlerim</span><span>›</span></div><div class="row"><span>TIKLADOY Hakkında</span><span>›</span></div></div>`,'person');home()}
window.addEventListener('hashchange',()=>route(location.hash.slice(1)||'home'));route(location.hash.slice(1)||'home');
