import { supabase } from './supabase.js'

let products=[]; let categories=[]; let session=null; let authMode='login';
let cart=JSON.parse(localStorage.getItem('tikladoy_cart')||'[]');
const app=document.querySelector('#app');
const money=v=>`${Number(v||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} ₺`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const saveCart=()=>localStorage.setItem('tikladoy_cart',JSON.stringify(cart));
const cartTotal=()=>cart.reduce((s,p)=>s+Number(p.unit_price??p.price??0),0);
const isBurger=p=>/burger|crispy|duble|classic|bbq|öğrenci menü/i.test(`${p.name} ${p.description||''}`);
const fallback=p=>`<div class="food-fallback ${isBurger(p)?'burger':''}"><span>${isBurger(p)?'🍔':'🍽️'}</span><small>${esc(p.name)}</small></div>`;
const img=p=>p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">${fallback(p)}`:fallback(p);

async function load(){const [p,c]=await Promise.all([supabase.from('products').select('id,name,price,description,image_url,is_featured,seller_id,category_id').eq('is_active',true).order('created_at'),supabase.from('categories').select('id,name,slug,sort_order').eq('is_active',true).order('sort_order')]);products=p.data||[];categories=c.data||[]}
function shell(content,active='home'){app.innerHTML=`<div class="app-v2"><header class="top-v2"><div><small>TESLİMAT KONUMU</small><button>Konumunu seç⌄</button></div><button class="account-v2" id="accountBtn">${session?'●':'○'}</button></header>${content}<nav class="nav-v2">${[['home','⌂','Ana Sayfa'],['search','⌕','Keşfet'],['orders','▤','Siparişler'],['person','○','Hesabım']].map(([r,i,t])=>`<button class="${active===r?'active':''}" data-nav="${r}"><b>${i}</b><small>${t}</small>${r==='orders'&&cart.length?`<em>${cart.length}</em>`:''}</button>`).join('')}</nav></div>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>route(b.dataset.nav));document.querySelector('#accountBtn')?.addEventListener('click',()=>authPage())}
function categoriesStrip(){return `<div class="cat-v2">${categories.slice(0,8).map(c=>{const p=products.find(x=>x.category_id===c.id);return `<button data-cat="${c.id}"><div>${p?img(p):'<div class="food-fallback"><span>🍴</span></div>'}</div><span>${esc(c.name)}</span></button>`}).join('')}</div>`}
function card(p,wide=false){return `<article class="product-v2 ${wide?'wide':''}" data-open="${p.id}"><div class="pic-v2">${img(p)}</div><div class="body-v2"><div class="brand-v2">${isBurger(p)?'BURGERMY':'TIKLADOY'}</div><div class="title-v2"><h3>${esc(p.name)}</h3><button data-add="${p.id}">+</button></div><p>${esc(p.description||'Özenle hazırlanır, taze paketlenir ve siparişine hazır hale getirilir.')}</p><div class="foot-v2"><strong>${money(p.price)}</strong><span>İçerik ve seçenekler →</span></div></div></article>`}
function home(){const burger=products.filter(isBurger).slice(0,6);const pop=products.filter(p=>p.is_featured).slice(0,6);shell(`<section class="hero-v2"><span>TIKLADOY</span><h1>Ne yiyeceksen,<br><b>TIKLADOY.</b></h1><p>Fotoğrafını gör, içeriğini incele, seçeneklerini belirle ve siparişe ekle.</p></section><div class="search-v2"><b>⌕</b><input id="searchInput" placeholder="Yemek, marka veya ürün ara"></div><section class="sec-v2"><div class="sec-head"><h2>Kategoriler</h2><button id="allCats">Tümünü gör</button></div>${categoriesStrip()}</section>${burger.length?`<section class="sec-v2"><div class="burgermy-banner"><div><small>MARKA VİTRİNİ</small><h2>BURGERMY</h2><p>Burger, menü ve çıtır lezzetler. Ürüne dokun; büyük fotoğraf, açıklama ve seçenekler açılsın.</p></div><div>MY</div></div><div class="wide-list">${burger.map(p=>card(p,true)).join('')}</div></section>`:''}${pop.length?`<section class="sec-v2"><div class="sec-head"><h2>Çok sevilenler</h2></div><div class="grid-v2">${pop.map(p=>card(p)).join('')}</div></section>`:''}<section class="sec-v2"><div class="sec-head"><h2>Tüm lezzetler</h2></div><div class="grid-v2" id="grid">${products.slice(0,16).map(p=>card(p)).join('')}</div></section><button class="cart-v2" id="cartBtn"><span>${cart.length} ürün</span><b>Sepete Git • ${money(cartTotal())}</b></button>`,'home');bind();document.querySelector('#cartBtn').onclick=cartPage;document.querySelector('#allCats').onclick=()=>discover();document.querySelector('#searchInput').oninput=e=>{const q=e.target.value.toLocaleLowerCase('tr');const list=products.filter(p=>`${p.name} ${p.description||''}`.toLocaleLowerCase('tr').includes(q));document.querySelector('#grid').innerHTML=list.map(p=>card(p)).join('');bind()}}
function bind(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();const p=products.find(x=>x.id===b.dataset.add);cart.push({...p,unit_price:Number(p.price),selected_options:[]});saveCart();home()});document.querySelectorAll('[data-open]').forEach(c=>c.onclick=e=>{if(!e.target.closest('[data-add]'))detail(c.dataset.open)});document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>discover(b.dataset.cat))}
async function detail(id){const p=products.find(x=>x.id===id);if(!p)return;const {data:opts}=await supabase.from('product_options').select('id,name,is_required,min_select,max_select,sort_order,product_option_values(id,name,price_delta,is_default,sort_order)').eq('product_id',id).order('sort_order');const options=opts||[];shell(`<button class="back-v2" id="backBtn">← Geri</button><section class="detail-v2"><div class="detail-pic">${img(p)}</div><div class="detail-copy"><small>${isBurger(p)?'BURGERMY • TIKLADOY':'TIKLADOY'}</small><div class="detail-title"><h1>${esc(p.name)}</h1><b>${money(p.price)}</b></div><p>${esc(p.description||'Özenle hazırlanır. Aşağıdaki seçeneklerle siparişini kişiselleştirebilirsin.')}</p>${options.map((o,oi)=>`<section class="choice-v2"><header><div><h3>${esc(o.name)}</h3><small>${o.is_required?'Seçim gerekli':'İsteğe bağlı'}</small></div>${o.max_select>1?`<span>En fazla ${o.max_select}</span>`:''}</header>${(o.product_option_values||[]).map(v=>`<label><span><input type="${o.max_select===1?'radio':'checkbox'}" name="o${oi}" value="${v.id}" data-label="${esc(v.name)}" data-delta="${Number(v.price_delta||0)}" ${v.is_default?'checked':''}> ${esc(v.name)}</span><b>${Number(v.price_delta||0)>0?`+${money(v.price_delta)}`:'Dahil'}</b></label>`).join('')}</section>`).join('')}<div class="qty-v2"><button id="minus">−</button><strong id="qty">1</strong><button id="plus">+</button></div><button class="add-v2" id="addDetail"><span>Sepete Ekle</span><b id="detailTotal">${money(p.price)}</b></button></div></section>`,'home');let qty=1;const selected=()=>[...document.querySelectorAll('.choice-v2 input:checked')].map(x=>({id:x.value,name:x.dataset.label,price_delta:Number(x.dataset.delta||0)}));const unit=()=>Number(p.price)+selected().reduce((s,x)=>s+x.price_delta,0);const calc=()=>document.querySelector('#detailTotal').textContent=money(unit()*qty);document.querySelectorAll('.choice-v2 input').forEach(x=>x.onchange=calc);document.querySelector('#minus').onclick=()=>{qty=Math.max(1,qty-1);document.querySelector('#qty').textContent=qty;calc()};document.querySelector('#plus').onclick=()=>{qty++;document.querySelector('#qty').textContent=qty;calc()};document.querySelector('#backBtn').onclick=home;document.querySelector('#addDetail').onclick=()=>{const ops=selected();for(let i=0;i<qty;i++)cart.push({...p,unit_price:unit(),selected_options:ops});saveCart();cartPage()}}
function discover(cat='all'){const list=cat==='all'?products:products.filter(p=>p.category_id===cat);shell(`<section class="simple-v2"><small>KEŞFET</small><h1>Ne arıyorsun?</h1></section><div class="search-v2"><b>⌕</b><input id="discoverInput" placeholder="Ürün ara"></div><section class="sec-v2">${categoriesStrip()}</section><section class="sec-v2"><div class="grid-v2" id="grid">${list.map(p=>card(p)).join('')}</div></section>`,'search');bind();document.querySelector('#discoverInput').oninput=e=>{const q=e.target.value.toLocaleLowerCase('tr');document.querySelector('#grid').innerHTML=products.filter(p=>`${p.name} ${p.description||''}`.toLocaleLowerCase('tr').includes(q)).map(p=>card(p)).join('');bind()}}
function cartPage(){shell(`<section class="simple-v2"><small>SEPET</small><h1>Siparişin</h1><p>${cart.length} ürün</p></section><section class="cart-list-v2">${cart.length?cart.map((p,i)=>`<article><div class="cart-thumb">${img(p)}</div><div><b>${esc(p.name)}</b>${p.selected_options?.length?`<small>${p.selected_options.map(x=>esc(x.name)).join(' • ')}</small>`:''}<strong>${money(p.unit_price??p.price)}</strong></div><button data-del="${i}">×</button></article>`).join(''):'<p>Sepetin henüz boş.</p>'}</section>${cart.length?`<div class="sum-v2"><span>Toplam</span><b>${money(cartTotal())}</b></div><button class="checkout-v2" id="checkout">Ödemeye Geç</button>`:''}`,'orders');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.del,1);saveCart();cartPage()});if(document.querySelector('#checkout'))document.querySelector('#checkout').onclick=()=>session?checkout():authPage('Sipariş vermek için giriş yap.')}
function checkout(){shell(`<section class="simple-v2"><small>ÖDEME</small><h1>Siparişi tamamla</h1></section><div class="panel-v2"><div><span>Teslimat Adresi</span><b>V1 Test Adresi</b></div><div><span>Ödeme</span><b>Test / Tahsilat Yok</b></div><div><span>Toplam</span><b>${money(cartTotal())}</b></div><button class="checkout-v2" id="complete">Siparişi Oluştur</button></div>`,'orders');document.querySelector('#complete').onclick=createOrder}
async function createOrder(){const btn=document.querySelector('#complete');btn.disabled=true;btn.textContent='Sipariş oluşturuluyor…';if(!session?.user){authPage('Oturum süren dolmuş.');return}if(!cart.length)return cartPage();const sellerId=cart[0]?.seller_id;if(cart.some(p=>p.seller_id!==sellerId)){alert('Şimdilik tek siparişte aynı satıcının ürünleri bulunabilir.');return}const subtotal=cartTotal();const orderNo=`TKD-${Date.now().toString().slice(-8)}`;const {data:order,error}=await supabase.from('orders').insert({order_no:orderNo,user_id:session.user.id,seller_id:sellerId,status:'received',payment_status:'pending',payment_method:'test',subtotal,delivery_fee:0,discount_amount:0,total_amount:subtotal,estimated_min:20,estimated_max:30}).select().single();if(error){alert(error.message);return}const items=cart.map(p=>({order_id:order.id,product_id:p.id,product_name:p.name,quantity:1,unit_price:Number(p.unit_price??p.price),line_total:Number(p.unit_price??p.price)}));const {error:itemError}=await supabase.from('order_items').insert(items);if(itemError){alert(itemError.message);return}cart=[];saveCart();shell(`<section class="success-v2"><div>✓</div><h1>Siparişin Alındı!</h1><p>${esc(order.order_no)}</p><b>${money(order.total_amount)}</b><button class="checkout-v2" id="homeBtn">Ana Sayfaya Dön</button></section>`,'orders');document.querySelector('#homeBtn').onclick=home}
async function ordersPage(){if(!session?.user)return authPage('Siparişlerini görmek için giriş yap.');const {data,error}=await supabase.from('orders').select('id,order_no,status,total_amount,created_at').order('created_at',{ascending:false}).limit(30);shell(`<section class="simple-v2"><small>SİPARİŞLER</small><h1>Geçmiş siparişlerin</h1></section><div class="panel-v2">${error?esc(error.message):(data||[]).map(o=>`<div><span><b>${esc(o.order_no)}</b><small>${new Date(o.created_at).toLocaleString('tr-TR')}</small></span><b>${money(o.total_amount)}</b></div>`).join('')||'Henüz sipariş yok.'}</div>`,'orders')}
function authPage(note=''){shell(`<section class="simple-v2"><small>HESABIM</small><h1>${session?'Hoş geldin':'Giriş yap'}</h1><p>${note||''}</p></section>${session?`<div class="panel-v2"><div><span>${esc(session.user.email||'')}</span></div><button class="menu-v2" id="ordersBtn">Siparişlerim →</button><button class="checkout-v2 secondary" id="logout">Çıkış Yap</button></div>`:`<div class="tabs-v2"><button data-mode="login" class="${authMode==='login'?'active':''}">Giriş Yap</button><button data-mode="register" class="${authMode==='register'?'active':''}">Kayıt Ol</button></div><div class="form-v2">${authMode==='register'?'<input id="name" placeholder="Ad Soyad">':''}<input id="email" type="email" placeholder="E-posta"><input id="password" type="password" placeholder="Şifre"><button class="checkout-v2" id="authSubmit">${authMode==='login'?'Giriş Yap':'Hesap Oluştur'}</button><div id="authStatus"></div></div>`}`,'person');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;authPage()});document.querySelector('#ordersBtn')?.addEventListener('click',ordersPage);document.querySelector('#logout')?.addEventListener('click',async()=>{await supabase.auth.signOut();session=null;authPage('Çıkış yapıldı.')});document.querySelector('#authSubmit')?.addEventListener('click',submitAuth)}
async function submitAuth(){const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,name=document.querySelector('#name')?.value.trim(),status=document.querySelector('#authStatus');if(!email||password.length<6){status.textContent='Geçerli e-posta ve en az 6 karakter şifre gir.';return}if(authMode==='login'){const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){status.textContent=error.message;return}session=data.session;authPage('Giriş başarılı.');return}const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error){status.textContent=error.message;return}session=data.session;if(session)authPage('Hesabın oluşturuldu.');else status.textContent='Hesabın oluşturuldu. E-posta doğrulama bağlantısını kontrol et.'}
function route(r){if(r==='search')return discover();if(r==='orders')return ordersPage();if(r==='person')return authPage();home()}
async function start(){shell('<div class="loading-v2">TIKLADOY yükleniyor…</div>');const {data:{session:s}}=await supabase.auth.getSession();session=s;supabase.auth.onAuthStateChange((_e,s)=>session=s);await load();home()}
start();
